import type { Metadata } from "next";
import { roboto_mono } from './fonts'
import "./globals.css";
import { Header } from "./components/Header";
import { Sidebar } from "./components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_mono.className}>
        <Header />
        <div className="wrapper">
      
          <Sidebar />

          <main>
            {children}
          </main>
        </div>
        </body>
    </html>
  );
}
